import { useEffect, useState, useCallback } from "react";
import { View, Text, StyleSheet, ScrollView, SafeAreaView, RefreshControl, TouchableOpacity } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import api from "@/services/api";
import { getUser } from "@/services/storage";

interface Analytics {
  coupons_generated_total: number;
  redemptions_total: number;
  redemption_rate_pct: number;
  avg_discount_pct: number;
  wallet_spent_total_cents: number;
  coupons_by_hour: Array<{ hour: number; count: number }>;
  top_products: Array<{ name: string; redemptions: number }>;
  recent_redemptions: Array<{ headline: string; cashback_cents: number; redeemed_at: string; discount_pct: number }>;
}

export default function AnalyticsScreen() {
  const router = useRouter();
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [shopId, setShopId] = useState<number | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    const user = await getUser();
    if (!user) return;
    const { data: shops } = await api.get(`/api/merchants/shop/${user.user_id}`);
    if (shops.length === 0) return;
    setShopId(shops[0].id);
    const { data } = await api.get(`/api/analytics/merchant/${shops[0].id}`);
    setAnalytics(data);
  }, []);

  useEffect(() => { load(); }, [load]);
  const onRefresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };

  const maxCount = analytics ? Math.max(...analytics.coupons_by_hour.map((h) => h.count), 1) : 1;

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        contentContainerStyle={styles.scroll}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#F97316" />}
      >
        <TouchableOpacity onPress={() => router.back()} style={styles.back}>
          <Text style={styles.backText}>← Dashboard</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Full Analytics</Text>

        {analytics && (
          <>
            <View style={styles.statsGrid}>
              <StatBox label="Total Generated" value={analytics.coupons_generated_total} color="#3B82F6" />
              <StatBox label="Total Redeemed" value={analytics.redemptions_total} color="#4ADE80" />
              <StatBox label="Redemption Rate" value={`${analytics.redemption_rate_pct}%`} color="#F97316" />
              <StatBox label="Avg Discount" value={`${analytics.avg_discount_pct}%`} color="#A855F7" />
            </View>

            <View style={styles.totalSpent}>
              <Text style={styles.totalSpentLabel}>Total Cashback Paid Out</Text>
              <Text style={styles.totalSpentVal}>€{(analytics.wallet_spent_total_cents / 100).toFixed(2)}</Text>
            </View>

            {/* Hourly bar chart */}
            <Text style={styles.sectionTitle}>Coupons Generated by Hour</Text>
            <View style={styles.chart}>
              {analytics.coupons_by_hour.map((h) => (
                <View key={h.hour} style={styles.barCol}>
                  <View style={[styles.bar, { height: Math.max(4, (h.count / maxCount) * 80) }]} />
                  <Text style={styles.barLabel}>{h.hour}</Text>
                </View>
              ))}
              {analytics.coupons_by_hour.length === 0 && (
                <Text style={styles.empty}>No data yet</Text>
              )}
            </View>

            {/* Top products */}
            {analytics.top_products.length > 0 && (
              <>
                <Text style={styles.sectionTitle}>Top Products</Text>
                {analytics.top_products.map((p, i) => (
                  <View key={i} style={styles.productRow}>
                    <Text style={styles.productRank}>#{i + 1}</Text>
                    <Text style={styles.productName}>{p.name}</Text>
                    <Text style={styles.productRedeem}>{p.redemptions} redemptions</Text>
                  </View>
                ))}
              </>
            )}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function StatBox({ label, value, color }: { label: string; value: number | string; color: string }) {
  return (
    <View style={[styles.statBox, { borderColor: color }]}>
      <Text style={[styles.statVal, { color }]}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F172A" },
  scroll: { padding: 16, paddingBottom: 40 },
  back: { marginBottom: 16 },
  backText: { color: "#F97316", fontSize: 14 },
  title: { color: "#F8FAFC", fontSize: 24, fontWeight: "800", marginBottom: 20 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 16 },
  statBox: { width: "47%", backgroundColor: "#1E293B", borderRadius: 14, padding: 14, borderWidth: 1 },
  statVal: { fontSize: 26, fontWeight: "800", marginBottom: 4 },
  statLabel: { color: "#64748B", fontSize: 11 },
  totalSpent: { backgroundColor: "#1A0D00", borderRadius: 16, padding: 20, alignItems: "center", marginBottom: 24, borderWidth: 1, borderColor: "#F97316" },
  totalSpentLabel: { color: "#94A3B8", fontSize: 13, marginBottom: 4 },
  totalSpentVal: { color: "#F97316", fontSize: 32, fontWeight: "800" },
  sectionTitle: { color: "#94A3B8", fontSize: 12, fontWeight: "700", textTransform: "uppercase", marginBottom: 12, letterSpacing: 1 },
  chart: { flexDirection: "row", alignItems: "flex-end", height: 100, backgroundColor: "#1E293B", borderRadius: 12, padding: 12, marginBottom: 24, gap: 4 },
  barCol: { flex: 1, alignItems: "center", gap: 4 },
  bar: { width: "80%", backgroundColor: "#F97316", borderRadius: 3 },
  barLabel: { color: "#475569", fontSize: 9 },
  empty: { flex: 1, color: "#475569", textAlign: "center", alignSelf: "center" },
  productRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#1E293B", borderRadius: 10, padding: 12, marginBottom: 8 },
  productRank: { color: "#F97316", fontWeight: "800", width: 28 },
  productName: { flex: 1, color: "#F8FAFC", fontSize: 14 },
  productRedeem: { color: "#64748B", fontSize: 12 },
});
